### ISSUE TITLE
Company Address passed in `endCrowdfund` should be cross checked with Token one

### ISSUE THREAD

**Issue by Aniket-Engg** [SecureBlocks/Tuurnt#16]
In `endCrowdfund` of TuurntCrowdsale.sol, there should be a check that passed companyAddress should be same as passed in TuurntToken Contract.

**Comment by vpanwar821** [comment]
We have given the functionality in `endCrowdfund ` that owner can pass the company address where the remaining tokens would go after the end of crowdsale.
