### ISSUE TITLE
startDate needs to be passed as a parameter in crowdsale contract

### ISSUE THREAD

**Issue by Aniket-Engg** [SecureBlocks/Tuurnt#17]
startDate needs to be passed as a parameter in crowdsale contract as per requirements. It will be replaced with `now` in current contract.

**Comment by Aniket-Engg** [comment]
@vpanwar821 Implement this too, as presale is only for 48 hours, it will be good to deploy the contracts before, so that user can be certain about sale opening.
@SatyamSB views?

**Comment by SatyamSB** [comment]
I am not sure. but yes it will help in promotions no need to panic at the last moment. I agree with @Aniket-Engg

**Comment by SatyamSB** [comment]
fix #18
